import { Key } from "@/keyboards/key";
import { KeyboardLayout } from ".";

// Polish Pro — ISO layout; base layer identical to US QWERTY; Polish diacritics via Option key
export const MACOS_PL_QWERTY: KeyboardLayout = [
  [
    new Key("`", { secondaryKey: "~" }),
    new Key("1", { secondaryKey: "!" }),
    new Key("2", { secondaryKey: "@" }),
    new Key("3", { secondaryKey: "#" }),
    new Key("4", { secondaryKey: "$" }),
    new Key("5", { secondaryKey: "%" }),
    new Key("6", { secondaryKey: "^" }),
    new Key("7", { secondaryKey: "&" }),
    new Key("8", { secondaryKey: "*" }),
    new Key("9", { secondaryKey: "(" }),
    new Key("0", { secondaryKey: ")" }),
    new Key("-", { secondaryKey: "_" }),
    new Key("=", { secondaryKey: "+" }),
    new Key(
      "Backspace",
      { position: ["bottom", "right"], width: 120, inert: true },
      "delete",
    ),
  ],
  [
    new Key(
      "Tab",
      { position: ["bottom", "left"], width: 120, inert: true },
      "tab",
    ),
    new Key("q", {}, "Q"),
    new Key("w", {}, "W"),
    new Key("e", {}, "E"),
    new Key("r", {}, "R"),
    new Key("t", {}, "T"),
    new Key("y", {}, "Y"),
    new Key("u", {}, "U"),
    new Key("i", {}, "I"),
    new Key("o", {}, "O"),
    new Key("p", {}, "P"),
    new Key("[", { secondaryKey: "{" }),
    new Key("]", { secondaryKey: "}" }),
    new Key("\\", { secondaryKey: "|" }),
  ],
  [
    new Key(
      "Caps Lock",
      { position: ["bottom", "left"], width: 142.5, inert: true },
      "caps lock",
    ),
    new Key("a", {}, "A"),
    new Key("s", {}, "S"),
    new Key("d", {}, "D"),
    new Key("f", {}, "F"),
    new Key("g", {}, "G"),
    new Key("h", {}, "H"),
    new Key("j", {}, "J"),
    new Key("k", {}, "K"),
    new Key("l", {}, "L"),
    new Key(";", { secondaryKey: ":" }),
    new Key("'", { secondaryKey: '"' }),
    new Key(
      "Enter",
      { position: ["bottom", "right"], width: 142.5, inert: true },
      "return",
    ),
  ],
  [
    new Key(
      "Shift",
      { position: ["bottom", "left"], width: 185, inert: true },
      "shift",
    ),
    new Key("z", {}, "Z"),
    new Key("x", {}, "X"),
    new Key("c", {}, "C"),
    new Key("v", {}, "V"),
    new Key("b", {}, "B"),
    new Key("n", {}, "N"),
    new Key("m", {}, "M"),
    new Key(",", { secondaryKey: "<" }),
    new Key(".", { secondaryKey: ">" }),
    new Key("/", { secondaryKey: "?" }),
    new Key(
      "Shift",
      { position: ["bottom", "right"], width: 185, inert: true },
      "shift",
    ),
  ],
  [
    new Key("fn", { position: ["bottom", "left"], inert: true }, "fn"),
    new Key(
      "Control",
      { position: ["bottom", "center"], inert: true, icon: "" },
      "control",
    ),
    new Key(
      "Alt",
      { position: ["bottom", "center"], inert: true, icon: "" },
      "option",
    ),
    new Key(
      "Meta",
      {
        position: ["bottom", "center"],
        width: 100,
        inert: true,
        icon: "",
      },
      "command",
    ),
    new Key(" ", { width: 420 }),
    new Key(
      "Meta",
      {
        position: ["bottom", "center"],
        width: 100,
        inert: true,
        icon: "",
      },
      "command",
    ),
    new Key(
      "Alt",
      { position: ["bottom", "center"], inert: true, icon: "" },
      "option",
    ),
    new Key(
      "ArrowLeft",
      {
        position: ["middle", "center"],
        inert: true,
        font: "bold 20px FontAwesome",
      },
      "",
    ),
    [
      new Key(
        "ArrowUp",
        {
          position: ["middle", "center"],
          inert: true,
          height: 37.5,
          font: "bold 20px FontAwesome",
        },
        "",
      ),
      new Key(
        "ArrowDown",
        {
          position: ["middle", "center"],
          height: 37.5,
          inert: true,
          font: "bold 20px FontAwesome",
        },
        "",
      ),
    ],
    new Key(
      "ArrowRight",
      {
        position: ["middle", "center"],
        inert: true,
        font: "bold 20px FontAwesome",
      },
      "",
    ),
  ],
];
