name: Building Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        env:
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.provisioning_profile }}
          PP_PATH: build/mastouchtyper.provisionprofile
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

      - name: Build/release Electron app
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags') }}

          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # windows_certs: ${{ secrets.windows_certs }}
          # windows_certs_password: ${{ secrets.windows_certs_password }}
        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Upload error log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: notarization-error.log
          path: notarization-error.log

      - name: Upload to App Store Connect
        if: startsWith(matrix.os, 'macos')
        run: |
          xcrun altool --validate-app -f dist/mas-universal/Touch\ Typer-${{github.ref_name}}-universal.pkg --type macos --apiKey ${{ secrets.api_key_id }} --apiIssuer ${{ secrets.api_key_issuer_id }} 
          xcrun altool --upload-app -f dist/mas-universal/Touch\ Typer-${{github.ref_name}}-universal.pkg --type macos --apiKey ${{ secrets.api_key_id }} --apiIssuer ${{ secrets.api_key_issuer_id }}

      - name: Upload to Windows Dev Center
        if: startsWith(matrix.os, 'windows')
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module -Name StoreBroker
          $password = ConvertTo-SecureString ${{ secrets.windows_dev_center_password }} -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ${{ secrets.windows_dev_center_username }}, $password
          Set-StoreBrokerAuthentication -TenantId ${{ secrets.windows_dev_center_tenant_id }} -Credential $credential
          Update-ApplicationSubmission -AppId "9NG3CCFL631D" -SubmissionDataPath "build/submission.json" -PackagePath ".\dist\Touch Typer ${{ github.ref_name }}.appx" -AutoCommit -Force
